### ISSUE TITLE
Getter: `Error: Virtual path "name" conflicts with a real path in the schema`

### ISSUE THREAD

**Issue by wxs77577** [hasezoey/typegoose#28]
## Versions

- NodeJS: 12
- Typegoose(NPM): 6.0.0-26
- Typegoose(GIT): commithash
- mongoose: 0.0.0
- mongodb: 0.0.0

## Code Example

```ts
import { getModelForClass, prop } from "@hasezoey/typegoose";
import * as mongoose from "mongoose"; // mongoose@5.6.13

class User {
    @prop()
    public username?: string;

    @prop()
    get name(){
      return this.username
    }
}
const UserModel = getModelForClass(User);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/test`, { useNewUrlParser: true });
    const user = new UserModel({ username: "user1" });
    await user.save()

    console.log(user);
})();
```

Output:

```
/Users/johnny/projects/test/typegoose-test/node_modules/mongoose/lib/schema.js:1712
    throw new Error('Virtual path "' + name + '"' +
          ^
Error: Virtual path "name" conflicts with a real path in the schema
    at Schema.virtual (/Users/johnny/projects/test/typegoose-test/node_modules/mongoose/lib/schema.js:1712:11)
    at Schema.<anonymous> (/Users/johnny/projects/test/typegoose-test/node_modules/mongoose/lib/schema.js:1869:12)
    at Array.forEach (<anonymous>)
    at Schema.loadClass (/Users/johnny/projects/test/typegoose-test/node_modules/mongoose/lib/schema.js:1858:47)
    at Object._buildSchema (/Users/johnny/projects/test/typegoose-test/node_modules/@hasezoey/typegoose/src/internal/schema.ts:49:7)
    at buildSchema (/Users/johnny/projects/test/typegoose-test/node_modules/@hasezoey/typegoose/src/typegoose.ts:141:9)
    at Object.getModelForClass (/Users/johnny/projects/test/typegoose-test/node_modules/@hasezoey/typegoose/src/typegoose.ts:96:42)
    at Object.<anonymous> (/Users/johnny/projects/test/typegoose-test/src/main.ts:12:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:158:12)
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
Thanks for pointing out that we dont have any virtual "get" & "set" tests, these are added now

its not really a bug, because virtuals dont accept any options & schema.loadClass (from mongoose) wouldnt loud them anyway, because mongoose dosnt use any decorators

please look at [this](https://hasezoey.github.io/typegoose/guides/known-issues/) too (it will be there when github updates it)

closing this for now
